from typing import Any, Optional
from .logger import Logger

class Data:
    def __init__(self, file: Optional[str] = ..., logger: Optional[Logger] = ...) -> None: ...
    def load(self) -> dict[str, Any]: ...
    def save(self, data: dict[str, Any]) -> None: ...
