from typing import Any, Final, Optional
from .logger import Logger

class Discogs:
    API_BASEURL: Final[str] = ...
    API_FORMAT: Final[str] = ...
    API_LIMIT: Final[int] = ...
    API_RATELIMIT_STATUS: Final[int] = ...
    API_RATELIMIT_TIME: Final[int] = ...
    def __init__(self, key: str, logger: Optional[Logger] = ...) -> None: ...
    def get_ratings(self, ratings: Optional[dict[str, Any]] = ...): ...
